version: '3.2'

services:

#================================================================================================
# JENKINS
#================================================================================================
  jenkins:
    restart: unless-stopped
    build:
      context: .
    container_name: nakama_jenkins
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data/jenkins:/var/jenkins_home
    environment:
      - JAVA_OPTS="-Djava.awt.headless=true"
      - JENKINS_VERSION=2.138
      - JENKINS_SHA=e1c280f1241999c9c7795a8ea3e5346debeb6be5e26744c13b03bc494dcef56c
      - TINI_VERSION=0.18.0
      - TINI_SHA=50a5bb62e3c4fdfb442da6d1530abb2b6afacc24
    ports:
      - "${JENKINS_HTTP_PORT:-9401}:8080"
      - "${JENKINS_JNLP_PORT:-9402}:50000" 
    # Allow Docker In Docker
    privileged: true     
